config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  root 'posts#index'

  resources :posts

  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, :desc, :text, presence: true

  scope :by_newest, -> {order(created_at: :desc)}
  scope :active,    -> {where(active: true)}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound,
              ActionController::RoutingError,
              ActionController::UnknownController,
              AbstractController::ActionNotFound,
    with: :render_404

  def render_404
    render 'errors/404', status: 404
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  PER_PAGE = 15

  def index
    @posts = Post.active.by_newest.page(params[:page]).per(PER_PAGE)
    respond_to do |format|
      format.html {render :index}
      format.rss  {render action: 'feed', layout: false}
    end
  end

  def show
    post = current_admin_user ? Post : Post.active
    @post = post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title
    @post.try(:title) ? @post.title : 'KvaziBlog - ruby / rails / web development'
  end

  def first_post_link
    post_path(Post.active.first) rescue '/'
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def display_text(text)
    highlight_syntax(text).html_safe
  end

  private

  def highlight_syntax(text)
    text.gsub(/\[code=([a-z]+)\](.+?)\[\/code\]/im) do
      "<pre data-highlight=#{$1}>#{CGI.escapeHTML($2)}</pre>"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head profile="http://www.w3.org/2005/10/profile">
    <title><%=page_title%></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render '/shared/analytics' %>
    <%= render '/shared/ie_hacks' %>
  </head>
  <body>
    <div id="page">
      <div id="title">
        <%= link_to(image_tag('rss.png'), posts_path(format: 'rss'), target: '_blank', class: 'rss-link')%>
        <h1>
          <%= link_to 'KvaziBlog.com', '/'%>
          <%= link_to '*', first_post_link, class: 'first-post-link'%>
        </h1>
        <p><%= mail_to 'parizhskiy@gmail.com', 'Me', target: '_blank' %> on <%= link_to 'GitHub', 'https://github.com/heel', target: '_blank'%> / <%= link_to 'LinkedIn', 'http://www.linkedin.com/in/parizhskiy', target: '_blank'%></p>
      </div>
      <div id="body">
        <div id="content">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/_index_post.html.erb
<h1><%= link_to post.title, post_path(post)%></h1>

<p class="desc">
  <%=post.desc%>
  <b><%=link_to "&hellip;".html_safe, post_path(post), class: 'more'%></b>
</p>

app/views/posts/index.html.erb
<%= render partial: 'posts/index_post', collection: @posts, as: :post %>

<%= paginate @posts %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div class="post-text">
  <%=display_text(@post.text)%>
</div>

<%= render '/shared/social_buttons'%>

<%= render '/shared/disqus'%>

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47012127-1', 'kvaziblog.com');
  ga('send', 'pageview');

</script>

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
  var disqus_shortname = 'Kvaziblog'; 

  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>

app/views/shared/_ie_hacks.html.erb
<!--[if IE]>
  <style type="text/css">
    #content {width: 770px; border-left: 2px solid #D1D1D1; border-right: 2px solid #D1D1D1; padding: 15px; margin: 0;}
    table {border: 2px solid #AAAAAA;}
  </style>
<![endif]-->

<!--[if IE 9]>
  <style type="text/css">
    #content {width: 766px; margin: 0 auto; padding: 15px; }
    table {border: 3px solid white; box-shadow: 0 0 10px #AAAAAA;}
  </style>
<![endif]-->

app/views/shared/_social_buttons.html.erb
<!-- TWITTER -->
<a href="https://twitter.com/share" class="twitter-share-button" data-url="<%=url_for(only_path: false)%>" data-lang="en" data-count="vertical">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<!-- GOOGLE PLUS -->
<div class="g-plusone" data-size="tall" data-href="<%=url_for(only_path: false)%>"></div>
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

<!-- FACEBOOK -->
&nbsp;<iframe src="//www.facebook.com/plugins/like.php?href=<%=url_for(only_path: false)%>&amp;width&amp;layout=box_count&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=65&amp;appId=436303576497786" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:65px;" allowTransparency="true"></iframe>